### ISSUE TITLE
Can not show pdf

### ISSUE THREAD

**Issue by DDChuru** [cesarvr/ionic2-basic-example#1]
I have followed the example for ionic 2 and can not seem to show the pdf it opens the home.html when i open the home page. Any help on how to access or open the pdf

**Comment by cesarvr** [comment]
maybe you forgot to install the plugin `cordova plugin add cordova-pdf-generator` ?

**Comment by DDChuru** [comment]
Thanks @cesarvr I had to delete the app on my device somehow it was not updating the app, working well.

**Comment by cesarvr** [comment]
cool  :)
